# Generated by Django 3.1.2 on 2020-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
