# Generated by Django 3.1.2 on 2020-11-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_set', to='community.post'),
        ),
    ]
