# Generated by Django 3.1.2 on 2020-11-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20201110_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_set', to='community.post'),
        ),
    ]
